name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
        - {os: ubuntu-latest, python-version: "3.7"}
        - {os: ubuntu-latest, python-version: "3.13"}
        - {os: macos-latest, python-version: "3.9"}
        - {os: macos-latest, python-version: "3.13"}
        - {os: windows-latest, python-version: "3.7"}
        - {os: windows-latest, python-version: "3.13"}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      shell: bash
      run: |
        python -mpip install --upgrade pip setuptools wheel &&
        python -mpip install . &&
        python -mpip list
    - name: Test
      shell: bash
      run: |
        python -munittest
